import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/request'

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>
      {/* Nav */}
      <Nav/>
      {/* Results */}
      <Results results={results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const laman = `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  const request = await fetch(laman)
  .then((res) => res.json());

  return {
    props: {
      results: request.results
    }
  }
}